# Generated by Django 5.0.6 on 2024-06-18 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='name',
            new_name='record_model',
        ),
    ]
