# Generated by Django 5.0.6 on 2024-06-18 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_name_record_record_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributevalues',
            name='validation',
        ),
    ]
