# Generated by Django 5.0.6 on 2024-06-18 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_attributevalues_validation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Record',
            new_name='Records',
        ),
    ]
